### ISSUE TITLE
gidserver doesn't compile with Apple LLVM version 7.3.0 (clang-703.0.31)

### ISSUE THREAD

**Issue by xennygrimmato** [ashmew2/gid-get-it-done#6]
I'm trying to compiler `gidserver.cpp` using:

```g++ gidserver.cpp -std=c++11 -Wall -lpthread -o gidserver```

I get 1 error:
```
gidserver.cpp:169:84: error: invalid operands to binary expression ('__bind<int &, sockaddr *, unsigned long>' and 'int')
    if(bind(listenfd, (struct sockaddr *) &listenaddr, sizeof(struct sockaddr_in)) < 0) {
```
Running `g++ --version` gives me:
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by xennygrimmato** [comment]
It seems that my compiler tries to use the `std::bind()`. When I try to use `::bind()`, I don't get the error.

**Comment by ashmew2** [comment]
nice, could you patch this?
I'll drop the using namespace std portion later.
If you want, you can fix everything like string to std::string under this same issue and open a PR

**Comment by xennygrimmato** [comment]
I'm getting rid of `using namespace std` and patching it.

**Comment by xennygrimmato** [comment]
I've created a Pull Request: #7 
Can you review it?

**Comment by ashmew2** [comment]
Merged. Thanks!
